server:
  port: 8080

spring:
  application:
    name: data-jpa
  datasource:
    url: jdbc:h2:mem:appdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    com.example: DEBUG
