server:
  port: 8080

spring:
  application:
    name: transactions
  datasource:
    url: jdbc:h2:mem:txdb;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.example: DEBUG
