server:
  port: 8080

spring:
  application:
    name: database-migration
  datasource:
    url: jdbc:h2:mem:appdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    com.example: DEBUG
