server:
  port: 8080

spring:
  application:
    name: observability
  
info:
  app:
    name: observability-demo
    version: 1.0.0
    description: A sample application demonstrating Actuator info endpoint.
  contact:
    email: support@example.com

management:
  metrics:
    distribution:
      percentiles:
        search.latency: 0.95,0.99
      percentiles-histogram:
        search.latency: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example: DEBUG

